[build]
  cmd = "go build -o ./tmp/main ./cmd/admin-server"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
  exclude_dir = ["tmp", "vendor", "web", "docs", "test", "migrations", "nginx", "scripts", ".git"]
  include_dir = ["cmd", "internal", "api", "configs"]
  # 监控admin相关的配置文件
  include_file = [
    "configs/server/admin-server.json",
    "configs/environments/local.yaml",
    "configs/environments/dev.yaml",
    "configs/base/ory.yaml"
  ]
  log = "build-errors.log"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"